@startuml

Interface Pintable{
    +pintar(Posicion inicio, Posicion fin, Dibujo dibujo)
}

Class LapizAbajo{
    +pintar(Posicion inicio, Posicion fin, Dibujo dibujo)
}

Class LapizArriba{
    +pintar(Posicion inicio, Posicion fin, Dibujo dibujo)
}

Pintable <|-- LapizAbajo
Pintable <|-- LapizArriba

Personaje *-- Pintable
Posicion <-- Pintable
Dibujo <-- Pintable

@enduml