@startuml

Class Personaje{
    -posicion
    -pintable
    +subirLapiz()
    +bajarLapiz()
    +mover(Posicion posicion, Dibujo dibujo)
    +obtenerPosicion(): Posicion
}

Abstract Class Bloque{}
Interface Pintable{}

Bloque ---> Personaje

Personaje *-- Pintable
Personaje *-- Posicion

Pintable <|-- LapizAbajo
Pintable <|-- LapizArriba

@enduml