@startuml

Abstract Class Bloque{
    +ejecutar(Pesonaje personaje, Dibujo dibujo)
    +ejecutarInversa(Personaje personaje, Dibujo dibujo)
}

Abstract Class BloqueComplejo{
    +agregarBloque(Bloque bloque)
    +ejecutarInversa(Personaje personaje, Dibujo dibujo)
}

Abstract Class BloqueRepetir{
    -cantidadRepeticiones
    +ejecutar(Pesonaje personaje, Dibujo dibujo)
    +ejecutarInversa(Personaje personaje, Dibujo dibujo)
}

Class Personaje{
    +subirLapiz()
    +bajarLapiz()
    +mover(Posicion posicion, Dibujo dibujo)
}

Class Dibujo{
    +crearTramo(Posicion inicio, Posicion fin)
    +contieneTramo(Tramo tramo): boolean
}

Class Tramo{
    +equals(Posicion): boolean
}

Interface Pintable{
    +pintar(Posicion inicio, Posicion fin, Dibujo dibujo)
}

Class LapizAbajo{
    +pintar(Posicion inicio, Posicion fin, Dibujo dibujo)
}

Class LapizArriba{
    +pintar(Posicion inicio, Posicion fin, Dibujo dibujo)
}

Class Posicion{
    +equals(Object objeto): boolean
    +sumar(Posicion posicion)
    +copy(): Posicion
}

Bloque <|-- BloqueComplejo
BloqueComplejo<|-- BloqueRepetir
Bloque ---> Personaje

Personaje "1"*--"1" Pintable
Personaje "1"*--"1" Posicion

Tramo "1"*--"2" Posicion
Dibujo "1"*--"0..*"Tramo

Pintable <|-- LapizAbajo
Pintable <|-- LapizArriba
Pintable --> Dibujo

@enduml